# Generated by Django 4.2 on 2023-07-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField(null=True)),
                ('humedad', models.FloatField(null=True)),
                ('precipitacion', models.FloatField(null=True)),
                ('nivel', models.FloatField(null=True)),
                ('caudal', models.FloatField(null=True)),
                ('radiacion', models.FloatField(null=True)),
                ('fecha', models.DateTimeField()),
                ('estacion', models.CharField(max_length=20)),
            ],
        ),
    ]
