# Generated by Django 4.2 on 2023-07-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_datos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=20)),
                ('coodenadas', models.CharField(max_length=50)),
                ('seguimiento', models.FloatField(null=True)),
                ('prealerta', models.FloatField(null=True)),
                ('alerta', models.FloatField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Datos',
            new_name='Data',
        ),
    ]
